const productos = [
  ...[
    ['Queso cremoso', 'kg'],
    ['Queso barra', 'kg'],
    ['Ricota', 'kg'],
    ['Leche TREGAR', 'pack de 15'],
    ['Huevos blancos', 'maple'],
    ['Huevos blancos', 'docena'],
    ['Huevos castaños', 'maple'],
    ['Huevos castaños', 'docena'],
    ['Almidón de mandioca', 'bolsa de 25 kg'],
    ['Almidón de mandioca', 'kg'],
    ['Almidón de maíz (maicena)', 'kg'],
    ['Almidón de maíz (maicena)', 'paquete de 500 g'],
    ['Avena tradicional', 'kg'],
    ['Avena tradicional', 'paquete de 500 g'],
    ['Coco rallado', 'kg'],
    ['Coco rallado (mayor)', 'kg'],
    ['Levadura seca Mauripan', 'caja'],
    ['Levadura seca Mauripan', 'paquete'],
    ['Azúcar impalpable', 'paquete de 1 kg'],
    ['Azúcar impalpable', 'paquete de 500 g'],
    ['Yerba muñeca', 'pack'],
    ['Azúcar', 'pack'],
    ['Dulce de leche repostero Santa María', 'balde de 10 kg'],
    ['Chocolate Carat', 'paquete de 800 g'],
    ['Mermelada de batata', 'balde de 10 kg'],
    ['Mermelada de membrillo', 'balde de 10 kg'],
    ['Dulce de membrillo', 'paquete de 5 kg'],
    ['Dulce de batata', 'paquete de 5 kg'],
    ['Guindas rojas/verdes', 'paquete de 5 kg'],
    ['Jalea fantasía', 'balde de 10 kg'],
    ['Harina 000 Andes', 'bolsa de 25 kg'],
    ['Harina 0000', 'bolsa de 25 kg']
  ].map(([nombre, unidad]) => ({ nombre, unidad, categoria: 'Mayorista', subcategoria: 'General' })),

  ...[
    ['Alfajores de maicena', 'unidad'],
    ['Alfajor de chocolate', 'unidad'],
    ['Alfajor de membrillo', 'unidad'],
    ['Facturas', 'unidad'],
    ['Medialunas', 'unidad'],
    ['Donas', 'unidad'],
    ['Lemon pie mediano', 'unidad'],
    ['Lemon pie grande', 'unidad'],
    ['Tarta de frutas mediana', 'unidad'],
    ['Tarta de frutas grande', 'unidad'],
    ['Tarta de ricota', 'kg'],
    ['Macitas', 'kg'],
    ['Macitas de avena, coco y maní', 'kg'],
    ['Pan dulce', 'unidad'],
    ['Pasta frola', 'unidad'],
    ['Pionono', 'kg'],
    ['Torta', 'kg'],
    ['Torta con mucho chocolate y frutillas', 'kg'],
    ['Torta en pote', 'kg'],
    ['Trufas', 'unidad'],
    ['Hojaldre', 'kg'],
    ['Kokitos de anís', 'kg'],
    ['Masas finas', 'kg'],
    ['Chiskake', 'unidad'],
    ['Browniee', 'kg'],
    ['Nega Maluca', 'kg'],
    ['Budín', 'kg'],
    ['Biscochuelo común', 'kg'],
    ['Rollito de canela', 'kg'],
    ['Trencitas de coco', 'unidad'],
    ['Prestigio (bomboncito de coco)', 'unidad'],
    ['Bomboncito tipo Ferrero', 'unidad'],
    ['Calsa virada', 'unidad'],
    ['Torta Rogel', 'kg'],
    ['Cookies', 'unidad'],
    ['Palmeritas', 'unidad'],
    ['Conito de dulce de leche', 'unidad']
  ].map(([nombre, unidad]) => ({ nombre, unidad, categoria: 'Minorista', subcategoria: 'Dulce' })),

  ...[
    ['Jamoncito', 'kg'],
    ['Chipitas de almidón', 'kg'],
    ['Pan de queso', 'kg'],
    ['Pan', 'kg'],
    ['Pan salvado', 'kg'],
    ['Pan rallado', 'kg'],
    ['Pan salvado con semillas', 'kg'],
    ['Pan saborizado', 'kg'],
    ['Pan para panchos', 'kg'],
    ['Prepiza', 'unidad'],
    ['Pizetas', 'kg'],
    ['Pan de hamburguesas', 'kg'],
    ['Tapas de empanadas con separador', 'unidad'],
    ['Tapas de empanadas con separador', 'docena'],
    ['Tapas de empanadas sin separador', 'unidad'],
    ['Tapas de empanadas sin separador', 'docena'],
    ['Tapas de pastelitos', 'unidad'],
    ['Tapas de pastelitos', 'docena'],
    ['Pascualina', 'unidad'],
    ['Torraditas y grisines', 'kg'],
    ['Cokitos azucaradas', 'kg'],
    ['Biscochitos hojaldrados con queso', 'kg'],
    ['Chinas', 'kg'],
    ['Chinas integrales', 'kg'],
    ['Bicochitos saborizados', 'kg'],
    ['Palitos salados', 'kg'],
    ['Fideos', 'unidad'],
    ['Pan de maíz', 'kg'],
    ['Biscochitos de grasa y cremonas', 'kg'],
    ['Torneaditos con queso', 'kg'],
    ['Reviro', 'kg'],
    ['Pan de papa', 'kg']
  ].map(([nombre, unidad]) => ({ nombre, unidad, categoria: 'Minorista', subcategoria: 'Salado' }))
];

module.exports = productos;
